#174910706 Align PTG template with current patterns
WindfallData/cookiecutter pull request #4
Opened 2020-10-22 18:50 UTC by ferraioc

[PR137](https://github.com/WindfallData/data-models/pull/137) into data-models has significantly updated the PTG model training patterns. This PR aligns the template with the new pattern. A user should be able to train a new model by simply creating a sql query and adding it to `train/train_sql.py`. The baseline model is also easily modifiable, if necessary.

2020-10-23 03:32 UTC, macrae requested changes
Thanks for your sizeable update to cookie-cutter @ferraioc !!!

This is really great - and because it's still early I took a fine-tooth comb to it.

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/requirements.txt
> +loaderbot
There are other dependencies imported in the train.py and score.py files not listed here, such as google and pandas. Seems like they should be added to the requirements.

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/score/score.sh
> +    --model_path "<path to model>"
These args don't get baked. The output of this in the final cookie is:
```
    --gcs_destination "<gcs destibation>" \
    --source_dataset "<bq source dataset>" \
    --source_table "<bq source table>" \
    --model_path "<path to model>"
```

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +from roc_it.windfall.notforprofit import NotForProfit
imported but unused statement

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +from zoolander.reports import plot_feature_importance, print_classification_results, plot_model_score_distribution
imported but unused statement `plot_model_score_distribution`

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +from train.logger import log_resampling_stat, log_feature_selection_stat
imported but unused statements

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +from train.train_sql import get_training_data, get_scoring_data
imported but unused statement `get_scoring_data`

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +        list(categorical_features.loc[:, ~categorical_features.columns.str.match('Unnamed')].features)
line lengths > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +    numeric_features = list(numeric_features.loc[:, ~numeric_features.columns.str.match('Unnamed')].features)
line lengths > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +    BinaryClassification(y_test, y_test_scores).save_artifacts(config.CONFUSION_THRESHOLD, f'./train/{ARTIFACT_DIR}',
line lengths > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +                        axis=1)
continuation line under-indented for visual indent

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/train.py
> +        logging.info(f"Loading all train configs in ./train/config to GCS")
f-string is missing placeholders

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/pipeline.py
> +def create_sampling_pipeline(sampling_parameters):
Can we add a simple docstring to this method?

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/pipeline.py
> +def create_training_pipeline(
Can we add a simple docstring to this method?

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/pipeline.py
> +                                  sampling_strategy=sampling_parameters["oversample"]["sampling_strategy"]
line lengths > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/pipeline.py
> +                                   sampling_strategy=sampling_parameters["undersample"]["sampling_strategy"]
line lengths > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +    return
no newline at end of file; also, is this supposed to return something?

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +def log_feature_selection_stat(n_features, pipeline):
docstring, please.

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +def log_resampling_stat(
docstring, please.

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +                 str(sum(pipeline.best_estimator_['featureselection'].estimator_.feature_importances_ >
line length > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +        generated = dict(train_pipeline.best_estimator_.steps).get('oversampler').sampling_strategy_.get('1')
line length > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +        reduced = dict(train_pipeline.best_estimator_.steps).get('undersampler').sampling_strategy_.get('0')
line length > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +            f"An additional {generated} ideal samples have been generated " + \
the backslash is redundant between brackets

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +            f"{non_ideal_count} non-ideal samples have been removed " + \
the backslash is redundant between brackets

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/logger.py
> +        f"After resampling there are {ideal_count} ideal labels and {non_ideal_count} " + \
the backslash is redundant between brackets

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/train/config/training_config.py
> +from sklearn.tree import DecisionTreeClassifier
imported but unused statements

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/score/score.py
> +from dateutil.relativedelta import relativedelta
imported but unused statement

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/score/score.py
> +warnings.filterwarnings('ignore')
this should be moved below import statements

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/score/score.py
> +from progressbar import ProgressBar
this formatting is all janky

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/score/score.py
> +    numeric_features = list(numeric_features.loc[:, ~numeric_features.columns.str.match('Unnamed')].features)
line length > 100

2020-10-23 03:32 UTC, macrae commented on {{cookiecutter.model_type}}/score/score.py
> +    X_score_features = pd.concat([X_score[numeric_features].astype(float), X_score[categorical_features].astype(str)],
line length > 100

2020-10-26 16:16 UTC, ferraioc commented on {{cookiecutter.model_type}}/requirements.txt
> +loaderbot
Hmm... I deliberately left them out because they're all pulled in from the req files in these three libraries. I think this is part of the ongoing conversation about the correct way to manage the dependencies between libraries. I'm not sure what the correct answer is here.

2020-10-26 16:41 UTC, ferraioc commented on {{cookiecutter.model_type}}/train/train.py
> +from roc_it.windfall.notforprofit import NotForProfit
There are some blocks of optional code that are currently commented out that use this. This specific import is for the RFM, which is dependent on writing a sql query to create the RFM features. Until that process is a bit more automated (jinja!), I'd like to keep it to allow the user to easily add in these figures when desired.

2020-10-26 16:42 UTC, ferraioc commented on {{cookiecutter.model_type}}/train/train.py
> +from zoolander.reports import plot_feature_importance, print_classification_results, plot_model_score_distribution
This one is used on lines 192 and 214.

2020-10-26 16:43 UTC, ferraioc commented on {{cookiecutter.model_type}}/train/train.py
> +from train.logger import log_resampling_stat, log_feature_selection_stat
These are used in an optional comment block on lines 142 and 146

2020-10-26 16:44 UTC, ferraioc commented on {{cookiecutter.model_type}}/train/train.py
> +from train.train_sql import get_training_data, get_scoring_data
Used in another optional code block to plot final score distributions, if the user desires.

2020-10-26 22:34 UTC, ferraioc commented on {{cookiecutter.model_type}}/score/score.sh
> +    --model_path "<path to model>"
Updated the model path and GCS destination to be baked in. The process for creating the source data tables isn't fully set yet, so for now I'm going to leave the user to update those. Once this is ironed out we can update this.

2020-10-26 22:46 UTC, macrae commented on {{cookiecutter.model_type}}/requirements.txt
> +loaderbot
I see. ok, let's give it a shot.

2020-10-26 22:52 UTC, macrae approved these changes

2020-10-26 22:54 UTC, merged